name: map_fields
description: Get fields from a map, simply, performing error handling errors.
version: 0.0.3
repository: https://github.com/isaukywhite/map_fields

environment:
  sdk: ">=2.17.5 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
